### ISSUE TITLE
could you maybe deploy the changes to npm?

### ISSUE THREAD

**Issue by HeIIow2** [HassaanAkbar/vue-zoomable#15]
See the title.

I'd be really great if you could find the time to deploy the new version with all the changes. Please no pressure though, else I will update the version I maintain, but using yours would be easier and better imo.

Thanks for the time <333

**Comment by ehassaan** [comment]
Sure, I can deploy in a couple of hours.

**Comment by HeIIow2** [comment]
@HassaanAkbar Thanks! 

I already deployed to my repo, but that'd be still good!  
Two things:

1. If you wanna look at how we used your library here https://www.competence-stuttgart.de/hallenplan/ _(only test data though)_
2. You may wanna change the default selector, it currently scales the control buttons, which was a honestly very funny bug xD

**Comment by ehassaan** [comment]
That's nice website. I have published the package. Will check the selector.
