### ISSUE TITLE
How to catch event of zoom or reset current zoom

### ISSUE THREAD

**Issue by ghost** [HassaanAkbar/vue-zoomable#17]
Hi, nice component. 

Trying to use it - need to reset zoom to default while switching different buttons. 
Setting ":zoom" option of plugin through the 

let zoomState = ref(0.5);

Not helps. 

Also tried computed state, no progress. 

Can you provide any example how to reset  or change zoom from outside code. Please.

**Comment by ehassaan** [comment]
You can use zoom prop to set the zoom. 
```
let zoom = ref(0.5);
.....
<vue-zoomable v-model:zoom="zoom" >...

```
https://github.com/HassaanAkbar/vue-zoomable/blob/e026823a79c21e8c6053065f0a4fed46dda4dbdf/src/examples/ReactivityDemo.vue#L110

**Comment by ehassaan** [comment]
Feel free to open if the issue still persists.
