### ISSUE TITLE
How to disable console spam of ComputedRefImpl

### ISSUE THREAD

**Issue by ghost** [HassaanAkbar/vue-zoomable#18]
On each zoom - there is a new console.log(...) in terminal :

![CleanShot 2023-11-06 at 11 45 27](https://github.com/HassaanAkbar/vue-zoomable/assets/5549987/0ae02e3c-ffa3-4576-a7aa-20db22305f90)

How can user disable it without intrusion in internal code?

**Comment by ehassaan** [comment]
Thanks for reporting the issue. I will look at it over the weekend.

**Comment by ehassaan** [comment]
Issue is fixed in v1.1.9
