### ISSUE TITLE
touch disabled after pan

### ISSUE THREAD

**Issue by Xiscollado** [HassaanAkbar/vue-zoomable#19]
Im trying to use the library but, after a pan i can´t touch anywhere in the screen. Do not happens with mouse, only on mobile. It´s like it loses focus on the page or something.

**Comment by ehassaan** [comment]
Thanks for reporting the issue @Xiscollado. Are you using it in web or Ionic?
Please share more details so I can try to reproduce.

Browser name/version: ?
Content inside vue-zoomable: svg or html?
Does it happen with pan using control buttons or only by touch/swipe?

**Comment by Xiscollado** [comment]
Thanks for the reply, i was working on brave, latest version. vue3 on web app. The content inside was an imgsrc. It happens when using touch and swipe. Didnt test with controls. Do not happens if only do zoom. As long as i do not swipe, it works.

**Comment by ehassaan** [comment]
@Xiscollado new version is published on npm

**Comment by Xiscollado** [comment]
Thanks!!, i ll check

**Comment by Xiscollado** [comment]
Now it works on mobile like a charm, but something happened to mouse version: Left click to pan stopped working and the "control +" message appears always even if not configured

![1](https://github.com/user-attachments/assets/073cf6c7-0668-4a0e-8bd4-88b6e7efa0f7)
![2](https://github.com/user-attachments/assets/2166b4ba-3f1e-4b89-b5f7-b96c4d0474e0)
![3](https://github.com/user-attachments/assets/9f56d2da-c124-4de0-ba2e-54d0923cc22c)
