### ISSUE TITLE
initial pan

### ISSUE THREAD

**Issue by mortegro** [HassaanAkbar/vue-zoomable#2]
Thanks for that great library! Why do you set the initial pan to 100? Is there a way to compensate for that, so that the element starts in its original position?

Thanks!

**Comment by ehassaan** [comment]
Hi @mortegro, I don't see any reason for this. We can set it to 0 by default and allow initial zoom and pan to be passed through props. Will that work for you?

**Comment by ehassaan** [comment]
Added initialPanX, initialPanY and initialZoom in new version.

**Comment by mortegro** [comment]
Works perfect! Thanks a lot!
