### ISSUE TITLE
Now it works on mobile like a charm, but something happened to mouse version: Left click to pan stopped working and the "control +" message appears always even if not configured

### ISSUE THREAD

**Issue by Xiscollado** [HassaanAkbar/vue-zoomable#22]
Now it works on mobile like a charm, but something happened to mouse version: Left click to pan stopped working and the "control +" message appears always even if not configured

![1](https://github.com/user-attachments/assets/073cf6c7-0668-4a0e-8bd4-88b6e7efa0f7)
![2](https://github.com/user-attachments/assets/2166b4ba-3f1e-4b89-b5f7-b96c4d0474e0)
![3](https://github.com/user-attachments/assets/9f56d2da-c124-4de0-ba2e-54d0923cc22c)

_Originally posted by @Xiscollado in https://github.com/HassaanAkbar/vue-zoomable/issues/19#issuecomment-2385073769_

**Comment by ehassaan** [comment]
Please use the latest version. I have separated the ScrollOverlay component.
