### ISSUE TITLE
Request for Center Zoom Support in vue-zoomable

### ISSUE THREAD

**Issue by momoca** [HassaanAkbar/vue-zoomable#29]
Hello,

First, thank you for the great work on vue-zoomable. It's a fantastic tool!

I would like to request support for zooming around the center point of the component, rather than zooming in and out from the cursor position. This feature would be useful in situations where maintaining focus on the center is essential for a better user experience.

Is this something that could be added in future releases?

Thank you for your time and consideration.

**Comment by ehassaan** [comment]
Hi @momoca , yes this is a known issue. But I could not give time to debug the reason for this. I can check on this over the weekend.

**Comment by ehassaan** [comment]
@momoca , update is published in v1.2.4. The issue is fixed for HTML content, but still persists for SVG content.
