### ISSUE TITLE
Unable to use library with Vue 3

### ISSUE THREAD

**Issue by vishwa-mehta-zygal** [HassaanAkbar/vue-zoomable#32]
"\"useTemplateRef\" is not exported by \"node_modules/vue/dist/vue.runtime.esm-bundler.js\", imported by \"node_modules/vue-zoomable/dist/vue-zoomable.mjs\".

On installation of vue-zoomable js library it throws above error.

It seems as if 'useTemplateRef' is not supported by my project which is used by library.

**Comment by ehassaan** [comment]
Looks like useTemplateRef is only available in vue 3.5+. Which version of vue are you using?

**Comment by ehassaan** [comment]
@vishwa-mehta-zygal  please use latest version v1.2.4
