### ISSUE TITLE
Missing "./dist/style.css" specifier in "vue-zoomable" package

### ISSUE THREAD

**Issue by parkjunghwan-reco** [HassaanAkbar/vue-zoomable#4]
hello. 
I can't import style.css.

Missing "./dist/style.css" specifier in "vue-zoomable" package
4:18:26 PM [vite] Internal server error: Missing "./dist/style.css" specifier in "vue-zoomable" package
  Plugin: vite:import-analysis

What should I do?
thank you

**Comment by ehassaan** [comment]
Hi, can you share your imports? You have to import both css and the component,

import VueZoomable from "vue-zoomable";
import "vue-zoomable/dist/style.css";

**Comment by ehassaan** [comment]
Fixed in new version. 
#v1.1.6
