### ISSUE TITLE
suggestion: Controll Button

### ISSUE THREAD

**Issue by HeIIow2** [HassaanAkbar/vue-zoomable#8]
First of, thanks for this great library!

The company I am employed at, needs control button. Due to this having come up in #6  before, I will implement the feature in a fork of this library. If you're interested, I will make a pull request.

The controll buttons are planned to be like this: 

![image](https://github.com/HassaanAkbar/vue-zoomable/assets/74311245/e2fc8b31-c1d5-4ec4-aa65-9dc0d03a489f)

I will add a new Prop, called `enableControllButton`, that is `false` by default. I will also implement all necessary props like `buttonZoomStep` etc.

| Name                 | type    | default | Description                                                                     |
| -------------------- | ------- | ------- | ------------------------------------------------------------------------------- |
| enableControllButton | boolean    | false   | Defines, if the controll buttons will be enabled.                               |
| buttonPanStep        | number  | 0.1     | Step size for pan on controll buttons                                           |
| buttonZoomStep       | number  | 0.1     | Step size for pan on controll buttons                                           |

Look [here](https://github.com/HeIIow2/vue-zoomable/tree/feat/controll_buttons) if you want updates on my development.

I am open to suggestions about how I implement it. You know the library better then I do after all.

Cheers :))

**Comment by ehassaan** [comment]
Sounds good. Please do add the props in the readme when you make PR.
Thanks for the contribution.

**Comment by HeIIow2** [comment]
> Sounds good. Please do add the props in the readme when you make PR. Thanks for the contribution.

I actually already did!

**Also note:**   
I am using [BEM](https://getbem.com/introduction/) as naming convention for classes. You could maybe consider doing so as well and writing it in the readme if you want to.  
Imho. just makes everything easyer to read and maintain after getting used to it.

**Comment by ehassaan** [comment]
Thanks for the suggestion. I am not actually a front-end developer. I have been working in data science domain for last few years. I have merged your PR and another one. But there are some errors on build. I will check it later.

**Comment by ehassaan** [comment]
I have added a check in your component to stay within min/max zoom.

**Comment by HeIIow2** [comment]
> Thanks for the suggestion. I am not actually a front-end developer. I have been working in data science domain for last few years. I have merged your PR and another one. But there are some errors on build. I will check it later.

Hey thank you very much. I'd gladly appreciate it! <3333

_Also sorry for not thinking about the min max myself xD_

**Comment by HeIIow2** [comment]
@HassaanAkbar I fixed your build error in another pr #11
